### PR TITLE
Fix documentations in classes

### LINKED ISSUE #252: Fix documentations in classes

### PR DESCRIPTION
**Pull request by limweijun**
Fixes #252

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/grade/GradeEditCommand.java [hunk 1]
```diff
@@ -106,8 +106,8 @@ public boolean equals(Object other) {
     }
 
     /**
-     * Stores the details to edit the person with. Each non-empty field value will replace the
-     * corresponding field value of the person.
+     * Stores the details to edit the grade with. The non-empty field value will replace the
+     * field value of the grade.
```
Comment (tensaida) [inline src/main/java/seedu/address/logic/commands/grade/GradeEditCommand.java:110]: Remove "The non-empty field value will replace the field value of the grade." Irrelevant here since `Grade` is an enum

File: src/main/java/seedu/address/model/AddressBook.java [hunk 2]
```diff
@@ -293,15 +294,13 @@ public ObservableMap<GradeKey, Grade> getGradeMap() {
...
     public boolean equals(Object other) {
-        // TODO: Add tasks to check
         return other == this // short circuit if same object
                 || (other instanceof AddressBook // instanceof handles nulls
                 && students.equals(((AddressBook) other).students));
     }
 
     @Override
     public int hashCode() {
-        // TODO: Add tasks to hashcode
```
Comment (tensaida) [inline src/main/java/seedu/address/model/AddressBook.java:304]: 🙌🏾

File: src/main/java/seedu/address/storage/JsonAdaptedTutorialGroup.java [hunk 3]
```diff
@@ -18,33 +18,29 @@ class JsonAdaptedTutorialGroup {
...
-     * Converts this Jackson-friendly adapted person object into the model's {@code Person} object.
+     * Converts this Jackson-friendly adapted tutorial group object into the model's {@code TutorialGroup} object.
      *
      * @throws IllegalValueException if there were any data constraints violated in the adapted person.
      */
     public TutorialGroup toModelType() throws IllegalValueException {
         if (name == null) {
             throw new IllegalValueException(String.format(MISSING_FIELD_MESSAGE_FORMAT, Name.class.getSimpleName()));
         }
-        //if (!Name.isValidName(name)) {
```
Comment (tensaida) [inline src/main/java/seedu/address/storage/JsonAdaptedTutorialGroup.java:44]: Good catch!

**Review by tensaida — APPROVED** [review]

File: src/main/java/seedu/address/logic/commands/grade/GradeEditCommand.java (hunk 1 above)
Comment (tensaida) [inline src/main/java/seedu/address/logic/commands/grade/GradeEditCommand.java]: Remove "The non-empty field value will replace the field value of the grade." Irrelevant here since Grade is an enum

**Review by tensaida — CHANGES_REQUESTED** [review]
Please

**Review by tensaida — APPROVED** [review]
LGTM!
